/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppARouteImport } from './routes/_app/a'
import { Route as AppBRouteImport } from './routes/_app/b'
import { Route as AppGestaoRouteImport } from './routes/_app/gestao'
import { Route as AppAIndexRouteImport } from './routes/_app/a/index'
import { Route as AppACasosRouteImport } from './routes/_app/a/casos'
import { Route as AppADistribuicaoRouteImport } from './routes/_app/a/distribuicao'
import { Route as AppAOperacaoRouteImport } from './routes/_app/a/operacao'
import { Route as AppARedeRouteImport } from './routes/_app/a/rede'
import { Route as AppARepassesRouteImport } from './routes/_app/a/repasses'
import { Route as AppBIndexRouteImport } from './routes/_app/b/index'
import { Route as AppBCasosRouteImport } from './routes/_app/b/casos'
import { Route as AppGestaoCamposNovosRouteImport } from './routes/_app/gestao/campos-novos'
import { Route as AppGestaoColisoesRouteImport } from './routes/_app/gestao/colisoes'
import { Route as AppGestaoDadosRouteImport } from './routes/_app/gestao/dados'
import { Route as AppGestaoFontesRouteImport } from './routes/_app/gestao/fontes'
import { Route as AppGestaoIntegracoesRouteImport } from './routes/_app/gestao/integracoes'
import { Route as AppGestaoRelatoriosRouteImport } from './routes/_app/gestao/relatorios'
import { Route as AppGestaoUsuariosRouteImport } from './routes/_app/gestao/usuarios'
import { Route as AppACasosIndexRouteImport } from './routes/_app/a/casos/index'
import { Route as AppACasosCasoIdRouteImport } from './routes/_app/a/casos/$casoId'
import { Route as AppACasosNovoRouteImport } from './routes/_app/a/casos/novo'
import { Route as AppBCasosIndexRouteImport } from './routes/_app/b/casos/index'
import { Route as AppBCasosCasoIdRouteImport } from './routes/_app/b/casos/$casoId'
import { Route as AppBCasosNovoRouteImport } from './routes/_app/b/casos/novo'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppARoute = AppARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => AppRoute,
} as any)
const AppBRoute = AppBRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRoute = AppGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AppRoute,
} as any)
const AppAIndexRoute = AppAIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppARoute,
} as any)
const AppACasosRoute = AppACasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => AppARoute,
} as any)
const AppADistribuicaoRoute = AppADistribuicaoRouteImport.update({
  id: '/distribuicao',
  path: '/distribuicao',
  getParentRoute: () => AppARoute,
} as any)
const AppAOperacaoRoute = AppAOperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => AppARoute,
} as any)
const AppARedeRoute = AppARedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => AppARoute,
} as any)
const AppARepassesRoute = AppARepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => AppARoute,
} as any)
const AppBIndexRoute = AppBIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBRoute,
} as any)
const AppBCasosRoute = AppBCasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => AppBRoute,
} as any)
const AppGestaoCamposNovosRoute = AppGestaoCamposNovosRouteImport.update({
  id: '/campos-novos',
  path: '/campos-novos',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppGestaoColisoesRoute = AppGestaoColisoesRouteImport.update({
  id: '/colisoes',
  path: '/colisoes',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppGestaoDadosRoute = AppGestaoDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppGestaoFontesRoute = AppGestaoFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppGestaoIntegracoesRoute = AppGestaoIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppGestaoRelatoriosRoute = AppGestaoRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppGestaoUsuariosRoute = AppGestaoUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppGestaoRoute,
} as any)
const AppACasosIndexRoute = AppACasosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppACasosRoute,
} as any)
const AppACasosCasoIdRoute = AppACasosCasoIdRouteImport.update({
  id: '/$casoId',
  path: '/$casoId',
  getParentRoute: () => AppACasosRoute,
} as any)
const AppACasosNovoRoute = AppACasosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppACasosRoute,
} as any)
const AppBCasosIndexRoute = AppBCasosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBCasosRoute,
} as any)
const AppBCasosCasoIdRoute = AppBCasosCasoIdRouteImport.update({
  id: '/$casoId',
  path: '/$casoId',
  getParentRoute: () => AppBCasosRoute,
} as any)
const AppBCasosNovoRoute = AppBCasosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppBCasosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/a': typeof AppARouteWithChildren
  '/b': typeof AppBRouteWithChildren
  '/gestao': typeof AppGestaoRouteWithChildren
  '/a/casos': typeof AppACasosRouteWithChildren
  '/a/distribuicao': typeof AppADistribuicaoRoute
  '/a/operacao': typeof AppAOperacaoRoute
  '/a/rede': typeof AppARedeRoute
  '/a/repasses': typeof AppARepassesRoute
  '/b/casos': typeof AppBCasosRouteWithChildren
  '/gestao/campos-novos': typeof AppGestaoCamposNovosRoute
  '/gestao/colisoes': typeof AppGestaoColisoesRoute
  '/gestao/dados': typeof AppGestaoDadosRoute
  '/gestao/fontes': typeof AppGestaoFontesRoute
  '/gestao/integracoes': typeof AppGestaoIntegracoesRoute
  '/gestao/relatorios': typeof AppGestaoRelatoriosRoute
  '/gestao/usuarios': typeof AppGestaoUsuariosRoute
  '/a/': typeof AppAIndexRoute
  '/b/': typeof AppBIndexRoute
  '/a/casos/$casoId': typeof AppACasosCasoIdRoute
  '/a/casos/novo': typeof AppACasosNovoRoute
  '/b/casos/$casoId': typeof AppBCasosCasoIdRoute
  '/b/casos/novo': typeof AppBCasosNovoRoute
  '/a/casos/': typeof AppACasosIndexRoute
  '/b/casos/': typeof AppBCasosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/gestao': typeof AppGestaoRouteWithChildren
  '/': typeof AppIndexRoute
  '/a/distribuicao': typeof AppADistribuicaoRoute
  '/a/operacao': typeof AppAOperacaoRoute
  '/a/rede': typeof AppARedeRoute
  '/a/repasses': typeof AppARepassesRoute
  '/gestao/campos-novos': typeof AppGestaoCamposNovosRoute
  '/gestao/colisoes': typeof AppGestaoColisoesRoute
  '/gestao/dados': typeof AppGestaoDadosRoute
  '/gestao/fontes': typeof AppGestaoFontesRoute
  '/gestao/integracoes': typeof AppGestaoIntegracoesRoute
  '/gestao/relatorios': typeof AppGestaoRelatoriosRoute
  '/gestao/usuarios': typeof AppGestaoUsuariosRoute
  '/a': typeof AppAIndexRoute
  '/b': typeof AppBIndexRoute
  '/a/casos/$casoId': typeof AppACasosCasoIdRoute
  '/a/casos/novo': typeof AppACasosNovoRoute
  '/b/casos/$casoId': typeof AppBCasosCasoIdRoute
  '/b/casos/novo': typeof AppBCasosNovoRoute
  '/a/casos': typeof AppACasosIndexRoute
  '/b/casos': typeof AppBCasosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/a': typeof AppARouteWithChildren
  '/_app/b': typeof AppBRouteWithChildren
  '/_app/gestao': typeof AppGestaoRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/a/casos': typeof AppACasosRouteWithChildren
  '/_app/a/distribuicao': typeof AppADistribuicaoRoute
  '/_app/a/operacao': typeof AppAOperacaoRoute
  '/_app/a/rede': typeof AppARedeRoute
  '/_app/a/repasses': typeof AppARepassesRoute
  '/_app/b/casos': typeof AppBCasosRouteWithChildren
  '/_app/gestao/campos-novos': typeof AppGestaoCamposNovosRoute
  '/_app/gestao/colisoes': typeof AppGestaoColisoesRoute
  '/_app/gestao/dados': typeof AppGestaoDadosRoute
  '/_app/gestao/fontes': typeof AppGestaoFontesRoute
  '/_app/gestao/integracoes': typeof AppGestaoIntegracoesRoute
  '/_app/gestao/relatorios': typeof AppGestaoRelatoriosRoute
  '/_app/gestao/usuarios': typeof AppGestaoUsuariosRoute
  '/_app/a/': typeof AppAIndexRoute
  '/_app/b/': typeof AppBIndexRoute
  '/_app/a/casos/$casoId': typeof AppACasosCasoIdRoute
  '/_app/a/casos/novo': typeof AppACasosNovoRoute
  '/_app/b/casos/$casoId': typeof AppBCasosCasoIdRoute
  '/_app/b/casos/novo': typeof AppBCasosNovoRoute
  '/_app/a/casos/': typeof AppACasosIndexRoute
  '/_app/b/casos/': typeof AppBCasosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/a'
    | '/b'
    | '/gestao'
    | '/a/casos'
    | '/a/distribuicao'
    | '/a/operacao'
    | '/a/rede'
    | '/a/repasses'
    | '/b/casos'
    | '/gestao/campos-novos'
    | '/gestao/colisoes'
    | '/gestao/dados'
    | '/gestao/fontes'
    | '/gestao/integracoes'
    | '/gestao/relatorios'
    | '/gestao/usuarios'
    | '/a/'
    | '/b/'
    | '/a/casos/$casoId'
    | '/a/casos/novo'
    | '/b/casos/$casoId'
    | '/b/casos/novo'
    | '/a/casos/'
    | '/b/casos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/gestao'
    | '/'
    | '/a/distribuicao'
    | '/a/operacao'
    | '/a/rede'
    | '/a/repasses'
    | '/gestao/campos-novos'
    | '/gestao/colisoes'
    | '/gestao/dados'
    | '/gestao/fontes'
    | '/gestao/integracoes'
    | '/gestao/relatorios'
    | '/gestao/usuarios'
    | '/a'
    | '/b'
    | '/a/casos/$casoId'
    | '/a/casos/novo'
    | '/b/casos/$casoId'
    | '/b/casos/novo'
    | '/a/casos'
    | '/b/casos'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/a'
    | '/_app/b'
    | '/_app/gestao'
    | '/_app/'
    | '/_app/a/casos'
    | '/_app/a/distribuicao'
    | '/_app/a/operacao'
    | '/_app/a/rede'
    | '/_app/a/repasses'
    | '/_app/b/casos'
    | '/_app/gestao/campos-novos'
    | '/_app/gestao/colisoes'
    | '/_app/gestao/dados'
    | '/_app/gestao/fontes'
    | '/_app/gestao/integracoes'
    | '/_app/gestao/relatorios'
    | '/_app/gestao/usuarios'
    | '/_app/a/'
    | '/_app/b/'
    | '/_app/a/casos/$casoId'
    | '/_app/a/casos/novo'
    | '/_app/b/casos/$casoId'
    | '/_app/b/casos/novo'
    | '/_app/a/casos/'
    | '/_app/b/casos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/a': {
      id: '/_app/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof AppARouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/b': {
      id: '/_app/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof AppBRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestao': {
      id: '/_app/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AppGestaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/a/': {
      id: '/_app/a/'
      path: '/'
      fullPath: '/a/'
      preLoaderRoute: typeof AppAIndexRouteImport
      parentRoute: typeof AppARoute
    }
    '/_app/a/casos': {
      id: '/_app/a/casos'
      path: '/casos'
      fullPath: '/a/casos'
      preLoaderRoute: typeof AppACasosRouteImport
      parentRoute: typeof AppARoute
    }
    '/_app/a/distribuicao': {
      id: '/_app/a/distribuicao'
      path: '/distribuicao'
      fullPath: '/a/distribuicao'
      preLoaderRoute: typeof AppADistribuicaoRouteImport
      parentRoute: typeof AppARoute
    }
    '/_app/a/operacao': {
      id: '/_app/a/operacao'
      path: '/operacao'
      fullPath: '/a/operacao'
      preLoaderRoute: typeof AppAOperacaoRouteImport
      parentRoute: typeof AppARoute
    }
    '/_app/a/rede': {
      id: '/_app/a/rede'
      path: '/rede'
      fullPath: '/a/rede'
      preLoaderRoute: typeof AppARedeRouteImport
      parentRoute: typeof AppARoute
    }
    '/_app/a/repasses': {
      id: '/_app/a/repasses'
      path: '/repasses'
      fullPath: '/a/repasses'
      preLoaderRoute: typeof AppARepassesRouteImport
      parentRoute: typeof AppARoute
    }
    '/_app/b/': {
      id: '/_app/b/'
      path: '/'
      fullPath: '/b/'
      preLoaderRoute: typeof AppBIndexRouteImport
      parentRoute: typeof AppBRoute
    }
    '/_app/b/casos': {
      id: '/_app/b/casos'
      path: '/casos'
      fullPath: '/b/casos'
      preLoaderRoute: typeof AppBCasosRouteImport
      parentRoute: typeof AppBRoute
    }
    '/_app/gestao/campos-novos': {
      id: '/_app/gestao/campos-novos'
      path: '/campos-novos'
      fullPath: '/gestao/campos-novos'
      preLoaderRoute: typeof AppGestaoCamposNovosRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/_app/gestao/colisoes': {
      id: '/_app/gestao/colisoes'
      path: '/colisoes'
      fullPath: '/gestao/colisoes'
      preLoaderRoute: typeof AppGestaoColisoesRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/_app/gestao/dados': {
      id: '/_app/gestao/dados'
      path: '/dados'
      fullPath: '/gestao/dados'
      preLoaderRoute: typeof AppGestaoDadosRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/_app/gestao/fontes': {
      id: '/_app/gestao/fontes'
      path: '/fontes'
      fullPath: '/gestao/fontes'
      preLoaderRoute: typeof AppGestaoFontesRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/_app/gestao/integracoes': {
      id: '/_app/gestao/integracoes'
      path: '/integracoes'
      fullPath: '/gestao/integracoes'
      preLoaderRoute: typeof AppGestaoIntegracoesRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/_app/gestao/relatorios': {
      id: '/_app/gestao/relatorios'
      path: '/relatorios'
      fullPath: '/gestao/relatorios'
      preLoaderRoute: typeof AppGestaoRelatoriosRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/_app/gestao/usuarios': {
      id: '/_app/gestao/usuarios'
      path: '/usuarios'
      fullPath: '/gestao/usuarios'
      preLoaderRoute: typeof AppGestaoUsuariosRouteImport
      parentRoute: typeof AppGestaoRoute
    }
    '/_app/a/casos/': {
      id: '/_app/a/casos/'
      path: '/'
      fullPath: '/a/casos/'
      preLoaderRoute: typeof AppACasosIndexRouteImport
      parentRoute: typeof AppACasosRoute
    }
    '/_app/a/casos/$casoId': {
      id: '/_app/a/casos/$casoId'
      path: '/$casoId'
      fullPath: '/a/casos/$casoId'
      preLoaderRoute: typeof AppACasosCasoIdRouteImport
      parentRoute: typeof AppACasosRoute
    }
    '/_app/a/casos/novo': {
      id: '/_app/a/casos/novo'
      path: '/novo'
      fullPath: '/a/casos/novo'
      preLoaderRoute: typeof AppACasosNovoRouteImport
      parentRoute: typeof AppACasosRoute
    }
    '/_app/b/casos/': {
      id: '/_app/b/casos/'
      path: '/'
      fullPath: '/b/casos/'
      preLoaderRoute: typeof AppBCasosIndexRouteImport
      parentRoute: typeof AppBCasosRoute
    }
    '/_app/b/casos/$casoId': {
      id: '/_app/b/casos/$casoId'
      path: '/$casoId'
      fullPath: '/b/casos/$casoId'
      preLoaderRoute: typeof AppBCasosCasoIdRouteImport
      parentRoute: typeof AppBCasosRoute
    }
    '/_app/b/casos/novo': {
      id: '/_app/b/casos/novo'
      path: '/novo'
      fullPath: '/b/casos/novo'
      preLoaderRoute: typeof AppBCasosNovoRouteImport
      parentRoute: typeof AppBCasosRoute
    }
  }
}

interface AppACasosRouteChildren {
  AppACasosCasoIdRoute: typeof AppACasosCasoIdRoute
  AppACasosNovoRoute: typeof AppACasosNovoRoute
  AppACasosIndexRoute: typeof AppACasosIndexRoute
}

const AppACasosRouteChildren: AppACasosRouteChildren = {
  AppACasosCasoIdRoute: AppACasosCasoIdRoute,
  AppACasosNovoRoute: AppACasosNovoRoute,
  AppACasosIndexRoute: AppACasosIndexRoute,
}

const AppACasosRouteWithChildren = AppACasosRoute._addFileChildren(
  AppACasosRouteChildren,
)

interface AppARouteChildren {
  AppACasosRoute: typeof AppACasosRouteWithChildren
  AppADistribuicaoRoute: typeof AppADistribuicaoRoute
  AppAOperacaoRoute: typeof AppAOperacaoRoute
  AppARedeRoute: typeof AppARedeRoute
  AppARepassesRoute: typeof AppARepassesRoute
  AppAIndexRoute: typeof AppAIndexRoute
}

const AppARouteChildren: AppARouteChildren = {
  AppACasosRoute: AppACasosRouteWithChildren,
  AppADistribuicaoRoute: AppADistribuicaoRoute,
  AppAOperacaoRoute: AppAOperacaoRoute,
  AppARedeRoute: AppARedeRoute,
  AppARepassesRoute: AppARepassesRoute,
  AppAIndexRoute: AppAIndexRoute,
}

const AppARouteWithChildren = AppARoute._addFileChildren(AppARouteChildren)

interface AppBCasosRouteChildren {
  AppBCasosCasoIdRoute: typeof AppBCasosCasoIdRoute
  AppBCasosNovoRoute: typeof AppBCasosNovoRoute
  AppBCasosIndexRoute: typeof AppBCasosIndexRoute
}

const AppBCasosRouteChildren: AppBCasosRouteChildren = {
  AppBCasosCasoIdRoute: AppBCasosCasoIdRoute,
  AppBCasosNovoRoute: AppBCasosNovoRoute,
  AppBCasosIndexRoute: AppBCasosIndexRoute,
}

const AppBCasosRouteWithChildren = AppBCasosRoute._addFileChildren(
  AppBCasosRouteChildren,
)

interface AppBRouteChildren {
  AppBCasosRoute: typeof AppBCasosRouteWithChildren
  AppBIndexRoute: typeof AppBIndexRoute
}

const AppBRouteChildren: AppBRouteChildren = {
  AppBCasosRoute: AppBCasosRouteWithChildren,
  AppBIndexRoute: AppBIndexRoute,
}

const AppBRouteWithChildren = AppBRoute._addFileChildren(AppBRouteChildren)

interface AppGestaoRouteChildren {
  AppGestaoCamposNovosRoute: typeof AppGestaoCamposNovosRoute
  AppGestaoColisoesRoute: typeof AppGestaoColisoesRoute
  AppGestaoDadosRoute: typeof AppGestaoDadosRoute
  AppGestaoFontesRoute: typeof AppGestaoFontesRoute
  AppGestaoIntegracoesRoute: typeof AppGestaoIntegracoesRoute
  AppGestaoRelatoriosRoute: typeof AppGestaoRelatoriosRoute
  AppGestaoUsuariosRoute: typeof AppGestaoUsuariosRoute
}

const AppGestaoRouteChildren: AppGestaoRouteChildren = {
  AppGestaoCamposNovosRoute: AppGestaoCamposNovosRoute,
  AppGestaoColisoesRoute: AppGestaoColisoesRoute,
  AppGestaoDadosRoute: AppGestaoDadosRoute,
  AppGestaoFontesRoute: AppGestaoFontesRoute,
  AppGestaoIntegracoesRoute: AppGestaoIntegracoesRoute,
  AppGestaoRelatoriosRoute: AppGestaoRelatoriosRoute,
  AppGestaoUsuariosRoute: AppGestaoUsuariosRoute,
}

const AppGestaoRouteWithChildren = AppGestaoRoute._addFileChildren(
  AppGestaoRouteChildren,
)

interface AppRouteChildren {
  AppARoute: typeof AppARouteWithChildren
  AppBRoute: typeof AppBRouteWithChildren
  AppGestaoRoute: typeof AppGestaoRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppARoute: AppARouteWithChildren,
  AppBRoute: AppBRouteWithChildren,
  AppGestaoRoute: AppGestaoRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
