/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessaoAberta"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsuarioSessao"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            email: string;
                            nome: string;
                            /** @enum {string} */
                            papel: "admin" | "operador" | "auditor";
                            canais: ("plataforma_credor" | "lead_proprio")[];
                            ativo: boolean;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoUsuarioInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsuarioCriado"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    origem?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListaCasos"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoCasoInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CasoCriado"];
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusInvalido"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/pode-transferir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PodeTransferir"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MudarStatusInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusAlterado"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusInvalido"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    finalidade?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CasoDetalhe"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventoCaso"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/devedor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RevelarDevedorInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DevedorRevelado"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/acessos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AcessoDadoPessoal"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/distribuir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DistribuirInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Distribuicao"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/colisoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Colisao"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovaColisaoInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Criado"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ativos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ativo"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoAtivoInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Criado"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fontes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Fonte"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recuperadores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recuperador"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoRecuperadorInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Criado"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bureaus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bureau"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repasses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Repasse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repasses/{id}/pagar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** @enum {string} */
                            status: "Pago";
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Credor"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome: string;
                        cnpj?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Criado"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credores/{id}/mandatos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        inicio: string;
                        fim: string;
                        referencia: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Criado"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mandatos/{id}/revogar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": null;
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/juridico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JuridicoCaso"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/rito": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        rito: "judicial" | "extrajudicial" | "amigavel";
                        credorId: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            status: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/processo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        numeroCnj: string;
                        vara?: string;
                        comarca: string;
                        uf: string;
                        ajuizadoEm?: string;
                        /** @enum {string} */
                        liminar: "pendente" | "deferida" | "indeferida" | "revogada";
                        liminarEm?: string;
                        mandadoEm?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            status: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/extrajudicial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        via: "rtd" | "detran";
                        orgao: string;
                        clausulaDestaque: boolean;
                        notificadoEm?: string;
                        consolidadoEm?: string;
                        certidaoEm?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            status: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/mora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        meio: "carta_ar" | "cartorio" | "protesto" | "eletronico";
                        enviadaEm: string;
                        enderecoDoContrato: boolean;
                        comprovante: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            status: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/verificacoes-rj": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        resultado: "sem_registro" | "recuperacao_judicial" | "falencia";
                        fonte: string;
                        detalhe?: string;
                        /** @default false */
                        liberadoPeloJuridico?: boolean;
                        justificativa?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Criado"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/acoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AcaoCaso"][];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/transicao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        para: "Retomado";
                        em: unknown;
                        /** @enum {string} */
                        modalidade: "apreensao_judicial" | "apreensao_extrajudicial" | "entrega_voluntaria";
                        comprovante: string;
                        condutaConforme?: boolean;
                    } | {
                        /** @enum {string} */
                        para: "Em Custódia";
                        local: string;
                    } | {
                        /** @enum {string} */
                        para: "Suspenso" | "Curado" | "Removido pelo Banco" | "Não Localizado" | "Encerrado";
                        motivo: string;
                    } | {
                        /** @enum {string} */
                        para: "Em Enriquecimento" | "Enriquecido" | "Em Análise" | "Pronto para Campo" | "Aceito" | "Em Campo" | "Localizado" | "Entregue ao Credor";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            status: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id}/resistencia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        relato: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            status: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovaConsultaInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsultaAuditoria"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LinhaAuditoria"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/custos/bureau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustoBureau"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camila/prioridades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecomendacaoCamila"][];
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            erro: string;
                            pendentes: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErroInput: {
            erro: string;
        };
        TenantInput: {
            id: string;
            nome: string;
            sigla: string;
            logoUrl: string | null;
        };
        UsuarioSessaoInput: {
            id: string;
            email: string;
            nome: string;
            /** @enum {string} */
            papel: "admin" | "operador" | "auditor";
            canais: ("plataforma_credor" | "lead_proprio")[];
            canaisVisiveis: ("plataforma_credor" | "lead_proprio")[];
            tenant: components["schemas"]["TenantInput"];
            csrfToken: string;
        };
        SessaoAbertaInput: {
            usuario: components["schemas"]["UsuarioSessaoInput"];
            expiraEm: unknown;
        };
        UsuarioCriadoInput: {
            id: string;
            email: string;
            nome: string;
            /** @enum {string} */
            papel: "admin" | "operador" | "auditor";
            canais: ("plataforma_credor" | "lead_proprio")[];
        };
        CasoInput: {
            id: string;
            ativoId: string;
            fonteId: string;
            /** @enum {string} */
            origem: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            status: string;
            recuperadorId: string | null;
            recuperadorNome: string | null;
            prazoVinculo: unknown;
            prazoMaximo: unknown;
            canalLead: string | null;
            evidenciaLead: string | null;
            saldoDevedor: number | null;
            valorQuitacaoNegociado: number | null;
            valorPagoAoDevedor: number | null;
            /** @enum {string|null} */
            anuenciaCredor: "Pendente" | "Obtida" | "Negada" | null;
            renajudAtivo: boolean | null;
            gravameBaixado: boolean | null;
            criadoEm: unknown;
            atualizadoEm: unknown;
            placa: string;
            modelo: string | null;
            cidade: string | null;
            uf: string | null;
        };
        ListaCasosInput: {
            /** @enum {string} */
            origem: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            total: number;
            casos: components["schemas"]["CasoInput"][];
        };
        CasoCriadoInput: {
            id: string;
            /** @enum {string} */
            origem: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
        };
        PodeTransferirInput: {
            podeTransferir: boolean;
            pendencias: string[];
        };
        StatusAlteradoInput: {
            id: string;
            status: string;
        };
        StatusInvalidoInput: {
            erro: string;
            validos: string[];
        };
        ColisaoInput: {
            id: string;
            placa: string;
            casoPlataformaId: string;
            leadProprioRef: string | null;
            detectadoEm: unknown;
            /** @enum {string} */
            resolucao: "lead_descartado" | "prosseguiu_com_origem_independente";
            justificativa: string;
            evidenciaIndependente: string | null;
            operadorId: string;
        };
        CriadoInput: {
            id: string;
        };
        AtivoInput: {
            id: string;
            placa: string;
            chassi: string | null;
            modelo: string | null;
            ano: number | null;
            cor: string | null;
            devedorNome: string | null;
            devedorDoc: string | null;
            credorNome: string | null;
            valorDivida: number | null;
            cidade: string | null;
            uf: string | null;
            dataRecebimento: unknown;
            criadoEm: unknown;
        };
        FonteInput: {
            id: string;
            nome: string;
            /** @enum {string} */
            tipo: "Plataforma" | "Credor Direto" | "Lead Próprio";
            /** @enum {string} */
            ingestao: "Manual" | "Exportação" | "API";
            /** @enum {string} */
            finalidadePermitida: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            termoDeUsoUrl: string | null;
            credorNome: string | null;
        };
        RecuperadorInput: {
            id: string;
            nome: string;
            documento: string | null;
            telefone: string | null;
            cidades: string[];
            /** @enum {string} */
            status: "Ativo" | "Inativo" | "Suspenso";
            score: number;
            taxaRecuperacao: number;
            dataCadastro: unknown;
        };
        BureauInput: {
            id: string;
            nome: string;
            /** @enum {string} */
            tipo: "Crédito" | "Veicular" | "Localização" | "Judicial";
            contratoFornecedorId: string;
            custoConsulta: number;
        };
        RepasseInput: {
            id: string;
            recuperadorId: string;
            recuperadorNome: string;
            casoId: string;
            placa: string;
            valor: number;
            data: unknown;
            /** @enum {string} */
            status: "Pendente" | "Pago" | "Cancelado";
            /** @enum {string} */
            tipo: "Comissão" | "Ajuda de Custo" | "Bônus";
            observacao: string | null;
        };
        ConsultaAuditoriaInput: {
            id: string;
            casoId: string;
            /** @enum {string} */
            origemCaso: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            bureauId: string;
            contratoFornecedorId: string;
            /** @enum {string} */
            baseLegal: "execucao_contrato" | "legitimo_interesse" | "obrigacao_legal" | "consentimento";
            justificativa: string;
            operadorId: string;
            consultadoEm: unknown;
            camposRetornados: string[];
            retencaoAte: unknown;
            custo: number;
        };
        LinhaAuditoriaInput: {
            id: string;
            casoId: string;
            /** @enum {string} */
            origemCaso: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            bureauId: string;
            contratoFornecedorId: string;
            /** @enum {string} */
            baseLegal: "execucao_contrato" | "legitimo_interesse" | "obrigacao_legal" | "consentimento";
            justificativa: string;
            operadorId: string;
            consultadoEm: unknown;
            camposRetornados: string[];
            retencaoAte: unknown;
            custo: number;
            bureauNome: string;
            operadorNome: string;
        };
        CustoBureauInput: {
            nome: string;
            consultas: number;
            custoTotal: number;
        };
        RecomendacaoCamilaInput: {
            repasseId: string;
            prioridade: string;
            justificativa: string;
            riscoCancelamento: number;
        };
        LoginInput: {
            email: string;
            senha: string;
        };
        NovoUsuarioInput: {
            /** Format: email */
            email: string;
            nome: string;
            senha: string;
            /** @enum {string} */
            papel: "admin" | "operador" | "auditor";
            /** @default [] */
            canais: ("plataforma_credor" | "lead_proprio")[];
        };
        NovoCasoInput: {
            /** @enum {string} */
            origem: "plataforma_credor";
            id?: string;
            ativoId: string;
            fonteId: string;
            status: string;
            recuperadorId?: string;
            prazoVinculo?: unknown;
            prazoMaximo?: unknown;
        } | {
            /** @enum {string} */
            origem: "lead_proprio";
            id?: string;
            ativoId: string;
            fonteId: string;
            status: string;
            /** @enum {string} */
            canalLead: "Inbound Site" | "WhatsApp" | "Indicação" | "Parceria" | "Anúncio";
            evidenciaLead: string;
            saldoDevedor?: number;
            valorQuitacaoNegociado?: number;
            valorPagoAoDevedor?: number;
            /**
             * @default Pendente
             * @enum {string}
             */
            anuenciaCredor: "Pendente" | "Obtida" | "Negada";
            renajudAtivo: boolean;
            gravameBaixado: boolean;
        };
        MudarStatusInput: {
            status: string;
        };
        NovaColisaoInput: {
            placa: string;
            casoPlataformaId: string;
            leadProprioRef?: string;
            /** @enum {string} */
            resolucao: "lead_descartado" | "prosseguiu_com_origem_independente";
            justificativa: string;
            evidenciaIndependente?: string;
        };
        NovoAtivoInput: {
            id?: string;
            placa: string;
            chassi?: string;
            modelo?: string;
            ano?: number;
            cor?: string;
            devedorNome?: string;
            devedorDoc?: string;
            credorNome?: string;
            valorDivida?: number;
            cidade?: string;
            uf?: string;
            dataRecebimento?: unknown;
        };
        NovoRecuperadorInput: {
            id?: string;
            nome: string;
            documento?: string;
            telefone?: string;
            /** @default [] */
            cidades: string[];
            /**
             * @default Ativo
             * @enum {string}
             */
            status: "Ativo" | "Inativo" | "Suspenso";
            /** @default 0 */
            score: number;
            /** @default 0 */
            taxaRecuperacao: number;
        };
        NovaConsultaInput: {
            casoId: string;
            bureauId: string;
            /** @enum {string} */
            baseLegal: "execucao_contrato" | "legitimo_interesse" | "obrigacao_legal" | "consentimento";
            justificativa: string;
            /** @default [] */
            camposRetornados: string[];
        };
        CasoDetalheInput: {
            id: string;
            ativoId: string;
            fonteId: string;
            /** @enum {string} */
            origem: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            status: string;
            recuperadorId: string | null;
            recuperadorNome: string | null;
            prazoVinculo: unknown;
            prazoMaximo: unknown;
            canalLead: string | null;
            evidenciaLead: string | null;
            saldoDevedor: number | null;
            valorQuitacaoNegociado: number | null;
            valorPagoAoDevedor: number | null;
            /** @enum {string|null} */
            anuenciaCredor: "Pendente" | "Obtida" | "Negada" | null;
            renajudAtivo: boolean | null;
            gravameBaixado: boolean | null;
            criadoEm: unknown;
            atualizadoEm: unknown;
            placa: string;
            modelo: string | null;
            cidade: string | null;
            uf: string | null;
            ativo: {
                chassi: string | null;
                ano: number | null;
                cor: string | null;
                credorNome: string | null;
                valorDivida: number | null;
                dataRecebimento: unknown;
            };
            fonte: {
                nome: string;
                /** @enum {string} */
                tipo: "Plataforma" | "Credor Direto" | "Lead Próprio";
                credorNome: string | null;
            };
        };
        EventoCasoInput: {
            id: number;
            /** @enum {string} */
            tipo: "criado" | "status_alterado" | "distribuido" | "rito_definido" | "registro_juridico";
            statusDe: string | null;
            statusPara: string | null;
            usuarioNome: string | null;
            ocorridoEm: unknown;
            dados: {
                [key: string]: unknown;
            };
        };
        DevedorReveladoInput: {
            devedorNome: string | null;
            devedorDoc: string | null;
        };
        AcessoDadoPessoalInput: {
            id: string;
            usuarioNome: string;
            campos: string[];
            finalidade: string;
            acessadoEm: unknown;
        };
        DistribuicaoInput: {
            id: string;
            status: string;
            recuperadorId: string;
            prazoVinculo: unknown;
            prazoMaximo: unknown;
        };
        DistribuirInput: {
            recuperadorId: string;
            /** @default 24 */
            horasParaAceite: number;
            /** @default 10 */
            diasDePrazo: number;
        };
        RevelarDevedorInput: {
            finalidade: string;
        };
        MandatoInput: {
            id: string;
            credorId: string;
            inicio: string;
            fim: string;
            referencia: string;
            revogadoEm: unknown;
            vigente: boolean;
        };
        CredorInput: {
            id: string;
            nome: string;
            cnpj: string | null;
            ativo: boolean;
            mandatos: components["schemas"]["MandatoInput"][];
        };
        ProcessoJudicialInput: {
            numeroCnj: string;
            vara: string | null;
            comarca: string;
            uf: string;
            ajuizadoEm: string | null;
            /** @enum {string} */
            liminar: "pendente" | "deferida" | "indeferida" | "revogada";
            liminarEm: string | null;
            mandadoEm: string | null;
            atualizadoEm: unknown;
        };
        ProcedimentoExtrajudicialInput: {
            /** @enum {string} */
            via: "rtd" | "detran";
            orgao: string;
            clausulaDestaque: boolean;
            notificadoEm: string | null;
            consolidadoEm: string | null;
            certidaoEm: string | null;
            prazoNotificacao: string | null;
            atualizadoEm: unknown;
        };
        ProvaMoraInput: {
            /** @enum {string} */
            meio: "carta_ar" | "cartorio" | "protesto" | "eletronico";
            enviadaEm: string;
            enderecoDoContrato: boolean;
            comprovante: string;
            atualizadoEm: unknown;
        };
        VerificacaoRjInput: {
            id: number;
            /** @enum {string} */
            resultado: "sem_registro" | "recuperacao_judicial" | "falencia";
            fonte: string;
            detalhe: string | null;
            liberadoPeloJuridico: boolean;
            justificativa: string | null;
            usuarioNome: string | null;
            verificadoEm: unknown;
        };
        JuridicoCasoInput: {
            status: string;
            /** @enum {string|null} */
            rito: "judicial" | "extrajudicial" | "amigavel" | null;
            credor: {
                id: string;
                nome: string;
                cnpj: string | null;
                ativo: boolean;
            } | null;
            mandatoVigente: components["schemas"]["MandatoInput"] | null;
            /** @enum {string|null} */
            devedorTipo: "PF" | "PJ" | null;
            processo: components["schemas"]["ProcessoJudicialInput"] | null;
            extrajudicial: components["schemas"]["ProcedimentoExtrajudicialInput"] | null;
            mora: components["schemas"]["ProvaMoraInput"] | null;
            verificacoesRj: components["schemas"]["VerificacaoRjInput"][];
            retomada: {
                em: unknown;
                /** @enum {string} */
                modalidade: "apreensao_judicial" | "apreensao_extrajudicial" | "entrega_voluntaria";
                comprovante: string;
                purgaAte: unknown;
            } | null;
        };
        AcaoCasoInput: {
            para: string;
            rotulo: string;
            pendencias: string[];
        };
        Erro: {
            erro: string;
        };
        Tenant: {
            id: string;
            nome: string;
            sigla: string;
            logoUrl: string | null;
        };
        UsuarioSessao: {
            id: string;
            email: string;
            nome: string;
            /** @enum {string} */
            papel: "admin" | "operador" | "auditor";
            canais: ("plataforma_credor" | "lead_proprio")[];
            canaisVisiveis: ("plataforma_credor" | "lead_proprio")[];
            tenant: components["schemas"]["Tenant"];
            csrfToken: string;
        };
        SessaoAberta: {
            usuario: components["schemas"]["UsuarioSessao"];
            /** Format: date-time */
            expiraEm: string;
        };
        UsuarioCriado: {
            id: string;
            email: string;
            nome: string;
            /** @enum {string} */
            papel: "admin" | "operador" | "auditor";
            canais: ("plataforma_credor" | "lead_proprio")[];
        };
        Caso: {
            id: string;
            ativoId: string;
            fonteId: string;
            /** @enum {string} */
            origem: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            status: string;
            recuperadorId: string | null;
            recuperadorNome: string | null;
            /** Format: date-time */
            prazoVinculo: string | null;
            /** Format: date-time */
            prazoMaximo: string | null;
            canalLead: string | null;
            evidenciaLead: string | null;
            saldoDevedor: number | null;
            valorQuitacaoNegociado: number | null;
            valorPagoAoDevedor: number | null;
            /** @enum {string|null} */
            anuenciaCredor: "Pendente" | "Obtida" | "Negada" | null;
            renajudAtivo: boolean | null;
            gravameBaixado: boolean | null;
            /** Format: date-time */
            criadoEm: string;
            /** Format: date-time */
            atualizadoEm: string;
            placa: string;
            modelo: string | null;
            cidade: string | null;
            uf: string | null;
        };
        ListaCasos: {
            /** @enum {string} */
            origem: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            total: number;
            casos: components["schemas"]["Caso"][];
        };
        CasoCriado: {
            id: string;
            /** @enum {string} */
            origem: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
        };
        PodeTransferir: {
            podeTransferir: boolean;
            pendencias: string[];
        };
        StatusAlterado: {
            id: string;
            status: string;
        };
        StatusInvalido: {
            erro: string;
            validos: string[];
        };
        Colisao: {
            id: string;
            placa: string;
            casoPlataformaId: string;
            leadProprioRef: string | null;
            /** Format: date-time */
            detectadoEm: string;
            /** @enum {string} */
            resolucao: "lead_descartado" | "prosseguiu_com_origem_independente";
            justificativa: string;
            evidenciaIndependente: string | null;
            operadorId: string;
        };
        Criado: {
            id: string;
        };
        Ativo: {
            id: string;
            placa: string;
            chassi: string | null;
            modelo: string | null;
            ano: number | null;
            cor: string | null;
            devedorNome: string | null;
            devedorDoc: string | null;
            credorNome: string | null;
            valorDivida: number | null;
            cidade: string | null;
            uf: string | null;
            /** Format: date-time */
            dataRecebimento: string;
            /** Format: date-time */
            criadoEm: string;
        };
        Fonte: {
            id: string;
            nome: string;
            /** @enum {string} */
            tipo: "Plataforma" | "Credor Direto" | "Lead Próprio";
            /** @enum {string} */
            ingestao: "Manual" | "Exportação" | "API";
            /** @enum {string} */
            finalidadePermitida: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            termoDeUsoUrl: string | null;
            credorNome: string | null;
        };
        Recuperador: {
            id: string;
            nome: string;
            documento: string | null;
            telefone: string | null;
            cidades: string[];
            /** @enum {string} */
            status: "Ativo" | "Inativo" | "Suspenso";
            score: number;
            taxaRecuperacao: number;
            /** Format: date-time */
            dataCadastro: string;
        };
        Bureau: {
            id: string;
            nome: string;
            /** @enum {string} */
            tipo: "Crédito" | "Veicular" | "Localização" | "Judicial";
            contratoFornecedorId: string;
            custoConsulta: number;
        };
        Repasse: {
            id: string;
            recuperadorId: string;
            recuperadorNome: string;
            casoId: string;
            placa: string;
            valor: number;
            /** Format: date-time */
            data: string;
            /** @enum {string} */
            status: "Pendente" | "Pago" | "Cancelado";
            /** @enum {string} */
            tipo: "Comissão" | "Ajuda de Custo" | "Bônus";
            observacao: string | null;
        };
        ConsultaAuditoria: {
            id: string;
            casoId: string;
            /** @enum {string} */
            origemCaso: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            bureauId: string;
            contratoFornecedorId: string;
            /** @enum {string} */
            baseLegal: "execucao_contrato" | "legitimo_interesse" | "obrigacao_legal" | "consentimento";
            justificativa: string;
            operadorId: string;
            /** Format: date-time */
            consultadoEm: string;
            camposRetornados: string[];
            /** Format: date-time */
            retencaoAte: string;
            custo: number;
        };
        LinhaAuditoria: {
            id: string;
            casoId: string;
            /** @enum {string} */
            origemCaso: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            bureauId: string;
            contratoFornecedorId: string;
            /** @enum {string} */
            baseLegal: "execucao_contrato" | "legitimo_interesse" | "obrigacao_legal" | "consentimento";
            justificativa: string;
            operadorId: string;
            /** Format: date-time */
            consultadoEm: string;
            camposRetornados: string[];
            /** Format: date-time */
            retencaoAte: string;
            custo: number;
            bureauNome: string;
            operadorNome: string;
        };
        CustoBureau: {
            nome: string;
            consultas: number;
            custoTotal: number;
        };
        RecomendacaoCamila: {
            repasseId: string;
            prioridade: string;
            justificativa: string;
            riscoCancelamento: number;
        };
        Login: {
            email: string;
            senha: string;
        };
        NovoUsuario: {
            /** Format: email */
            email: string;
            nome: string;
            senha: string;
            /** @enum {string} */
            papel: "admin" | "operador" | "auditor";
            /** @default [] */
            canais: ("plataforma_credor" | "lead_proprio")[];
        };
        NovoCaso: {
            /** @enum {string} */
            origem: "plataforma_credor";
            id?: string;
            ativoId: string;
            fonteId: string;
            status: string;
            recuperadorId?: string;
            /** Format: date-time */
            prazoVinculo?: string;
            /** Format: date-time */
            prazoMaximo?: string;
        } | {
            /** @enum {string} */
            origem: "lead_proprio";
            id?: string;
            ativoId: string;
            fonteId: string;
            status: string;
            /** @enum {string} */
            canalLead: "Inbound Site" | "WhatsApp" | "Indicação" | "Parceria" | "Anúncio";
            evidenciaLead: string;
            saldoDevedor?: number;
            valorQuitacaoNegociado?: number;
            valorPagoAoDevedor?: number;
            /**
             * @default Pendente
             * @enum {string}
             */
            anuenciaCredor: "Pendente" | "Obtida" | "Negada";
            renajudAtivo: boolean;
            gravameBaixado: boolean;
        };
        MudarStatus: {
            status: string;
        };
        NovaColisao: {
            placa: string;
            casoPlataformaId: string;
            leadProprioRef?: string;
            /** @enum {string} */
            resolucao: "lead_descartado" | "prosseguiu_com_origem_independente";
            justificativa: string;
            evidenciaIndependente?: string;
        };
        NovoAtivo: {
            id?: string;
            placa: string;
            chassi?: string;
            modelo?: string;
            ano?: number;
            cor?: string;
            devedorNome?: string;
            devedorDoc?: string;
            credorNome?: string;
            valorDivida?: number;
            cidade?: string;
            uf?: string;
            /** Format: date-time */
            dataRecebimento?: string;
        };
        NovoRecuperador: {
            id?: string;
            nome: string;
            documento?: string;
            telefone?: string;
            /** @default [] */
            cidades: string[];
            /**
             * @default Ativo
             * @enum {string}
             */
            status: "Ativo" | "Inativo" | "Suspenso";
            /** @default 0 */
            score: number;
            /** @default 0 */
            taxaRecuperacao: number;
        };
        NovaConsulta: {
            casoId: string;
            bureauId: string;
            /** @enum {string} */
            baseLegal: "execucao_contrato" | "legitimo_interesse" | "obrigacao_legal" | "consentimento";
            justificativa: string;
            /** @default [] */
            camposRetornados: string[];
        };
        CasoDetalhe: {
            id: string;
            ativoId: string;
            fonteId: string;
            /** @enum {string} */
            origem: "plataforma_credor" | "lead_proprio";
            /** @enum {string} */
            finalidade: "recuperacao_para_credor" | "aquisicao_com_quitacao";
            status: string;
            recuperadorId: string | null;
            recuperadorNome: string | null;
            /** Format: date-time */
            prazoVinculo: string | null;
            /** Format: date-time */
            prazoMaximo: string | null;
            canalLead: string | null;
            evidenciaLead: string | null;
            saldoDevedor: number | null;
            valorQuitacaoNegociado: number | null;
            valorPagoAoDevedor: number | null;
            /** @enum {string|null} */
            anuenciaCredor: "Pendente" | "Obtida" | "Negada" | null;
            renajudAtivo: boolean | null;
            gravameBaixado: boolean | null;
            /** Format: date-time */
            criadoEm: string;
            /** Format: date-time */
            atualizadoEm: string;
            placa: string;
            modelo: string | null;
            cidade: string | null;
            uf: string | null;
            ativo: {
                chassi: string | null;
                ano: number | null;
                cor: string | null;
                credorNome: string | null;
                valorDivida: number | null;
                /** Format: date-time */
                dataRecebimento: string;
            };
            fonte: {
                nome: string;
                /** @enum {string} */
                tipo: "Plataforma" | "Credor Direto" | "Lead Próprio";
                credorNome: string | null;
            };
        };
        EventoCaso: {
            id: number;
            /** @enum {string} */
            tipo: "criado" | "status_alterado" | "distribuido" | "rito_definido" | "registro_juridico";
            statusDe: string | null;
            statusPara: string | null;
            usuarioNome: string | null;
            /** Format: date-time */
            ocorridoEm: string;
            dados: {
                [key: string]: unknown;
            };
        };
        DevedorRevelado: {
            devedorNome: string | null;
            devedorDoc: string | null;
        };
        AcessoDadoPessoal: {
            id: string;
            usuarioNome: string;
            campos: string[];
            finalidade: string;
            /** Format: date-time */
            acessadoEm: string;
        };
        Distribuicao: {
            id: string;
            status: string;
            recuperadorId: string;
            /** Format: date-time */
            prazoVinculo: string;
            /** Format: date-time */
            prazoMaximo: string;
        };
        Distribuir: {
            recuperadorId: string;
            /** @default 24 */
            horasParaAceite: number;
            /** @default 10 */
            diasDePrazo: number;
        };
        RevelarDevedor: {
            finalidade: string;
        };
        Mandato: {
            id: string;
            credorId: string;
            inicio: string;
            fim: string;
            referencia: string;
            /** Format: date-time */
            revogadoEm: string | null;
            vigente: boolean;
        };
        Credor: {
            id: string;
            nome: string;
            cnpj: string | null;
            ativo: boolean;
            mandatos: components["schemas"]["Mandato"][];
        };
        ProcessoJudicial: {
            numeroCnj: string;
            vara: string | null;
            comarca: string;
            uf: string;
            ajuizadoEm: string | null;
            /** @enum {string} */
            liminar: "pendente" | "deferida" | "indeferida" | "revogada";
            liminarEm: string | null;
            mandadoEm: string | null;
            /** Format: date-time */
            atualizadoEm: string;
        };
        ProcedimentoExtrajudicial: {
            /** @enum {string} */
            via: "rtd" | "detran";
            orgao: string;
            clausulaDestaque: boolean;
            notificadoEm: string | null;
            consolidadoEm: string | null;
            certidaoEm: string | null;
            prazoNotificacao: string | null;
            /** Format: date-time */
            atualizadoEm: string;
        };
        ProvaMora: {
            /** @enum {string} */
            meio: "carta_ar" | "cartorio" | "protesto" | "eletronico";
            enviadaEm: string;
            enderecoDoContrato: boolean;
            comprovante: string;
            /** Format: date-time */
            atualizadoEm: string;
        };
        VerificacaoRj: {
            id: number;
            /** @enum {string} */
            resultado: "sem_registro" | "recuperacao_judicial" | "falencia";
            fonte: string;
            detalhe: string | null;
            liberadoPeloJuridico: boolean;
            justificativa: string | null;
            usuarioNome: string | null;
            /** Format: date-time */
            verificadoEm: string;
        };
        JuridicoCaso: {
            status: string;
            /** @enum {string|null} */
            rito: "judicial" | "extrajudicial" | "amigavel" | null;
            credor: {
                id: string;
                nome: string;
                cnpj: string | null;
                ativo: boolean;
            } | null;
            mandatoVigente: components["schemas"]["Mandato"] | null;
            /** @enum {string|null} */
            devedorTipo: "PF" | "PJ" | null;
            processo: components["schemas"]["ProcessoJudicial"] | null;
            extrajudicial: components["schemas"]["ProcedimentoExtrajudicial"] | null;
            mora: components["schemas"]["ProvaMora"] | null;
            verificacoesRj: components["schemas"]["VerificacaoRj"][];
            retomada: {
                /** Format: date-time */
                em: string;
                /** @enum {string} */
                modalidade: "apreensao_judicial" | "apreensao_extrajudicial" | "entrega_voluntaria";
                comprovante: string;
                /** Format: date-time */
                purgaAte: string | null;
            } | null;
        };
        AcaoCaso: {
            para: string;
            rotulo: string;
            pendencias: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
